XnForum.UI.Web/Areas/Admin/Controllers/BadWordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XnForum.Services.Contracts.Interfaces;

namespace XnForum.UI.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BadWordsController : Controller
    {
        private IAdminService _adminService;

        public BadWordsController(IAdminService adminService)
        {
            _adminService = adminService;
        }
        
        public ActionResult Index()
        {
            return View(_adminService.GetAllBadWords());
        }

        [HttpPost]
        public ActionResult Add(string text)
        {
            _adminService.AddBadWord(text);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(string text)
        {
            _adminService.DeleteBadWord(text);
            return RedirectToAction("Index");
        }
    }
}

XnForum.UI.Web/Areas/Admin/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XnForum.Services.Contracts.Interfaces;

namespace XnForum.UI.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TagsController : Controller
    {
        private IAdminService _adminService;

        public TagsController(IAdminService adminService)
        {
            _adminService = adminService;
        }
        
        public ActionResult Index()
        {
            return View(_adminService.GetAllHtmlTags());
        }

        [HttpPost]
        public ActionResult Add(string tag)
        {
            _adminService.AddHtmlTag(tag);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(string tag)
        {
            _adminService.DeleteHtmlTag(tag);
            return RedirectToAction("Index");
        }
    }
}

XnForum.UI.Web/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XnForum.Services.Contracts.Interfaces;

namespace XnForum.UI.Web.Controllers
{
    public class ForumController : Controller
    {
        private IForumService _forumService;

        public ForumController(IForumService forumService)
        {
            _forumService = forumService;
        }

        //main page
        public ActionResult Index()
        {
            var model = _forumService.GetAllForumData();

            return View(model);
        }

        //forum
        public ActionResult Forum(int id, int page)
        {
            var model = _forumService.GetForum(id, page);

            return View(model);
        }
        
    }
}

XnForum.UI.Web/Controllers/ModeratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using XnForum.Services;
using XnForum.Services.Contracts.DTO;
using XnForum.Services.Contracts.Interfaces;
using XnForum.UI.Web.Extensions;

namespace XnForum.UI.Web.Controllers
{
    public class ModeratorController : Controller
    {
        private IModeratorService _moderatorService;

        public ModeratorController(IModeratorService moderatorService)
        {
            _moderatorService = moderatorService;
        }



        // GET: Moderator/Forum/{forumid?}
        public ActionResult Reports(int? id)
        {
            var model = _moderatorService.GetModeratorPage(User.Identity.GetUserId<int>(), id);

            return View(model);
        }


        //post details & actions
        public ActionResult Post(int id)
        {
            var model = _moderatorService.GetPostToEdit(User.Identity.GetUserId<int>(), id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Post(PostEditDto model)//saving
        {
            _moderatorService.EditPost(User.Identity.GetUserId<int>(), model);

            return RedirectToAction("Reports");
        }

        [HttpPost]
        public ActionResult PostDelete(int id)//delete
        {
            _moderatorService.DeletePost(User.Identity.GetUserId<int>(), id);

            return RedirectToAction("Reports");
        }

        [HttpPost]
        public ActionResult PostIgnore(int id)//ignore
        {
            _moderatorService.IgnorePostReports(User.Identity.GetUserId<int>(), id);

            return RedirectToAction("Reports");
        }

        public ActionResult History()
        {
            return View();
        }
    }
}

XnForum.UI.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Forum", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ogłoszenia", "Index", "AdminNotes")</li>
                    <li>@Html.ActionLink("Struktura", "Index", "Structure")</li>
                    <li>@Html.ActionLink("Moderatorzy", "Index", "Moderator")</li>
                    <li>@Html.ActionLink("Powody zgłoszeń", "Index", "ReportReason")</li>
                    <li>@Html.ActionLink("Zakazane słowa", "Index", "BadWords")</li>
                    <li>@Html.ActionLink("Tagi html", "Index", "Tags")</li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>