XnForum.UI.Web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using XnForum.Services.Contracts.DTO;
using XnForum.Services.Contracts.Interfaces;
using XnForum.UI.Web.Extensions;

namespace XnForum.UI.Web.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        private IMessageService _messageService;

        public MessageController(IMessageService messageService)
        {
            _messageService = messageService;
        }

        public ActionResult Messages(int page)
        {
            var model = _messageService.GetHeaderMessages(HttpContext.User.Identity.GetUserId<int>(), page);
            return View(model);
        }

        public ActionResult Talk(string login, int page)
        {
            var model = _messageService.GetTalk(HttpContext.User.Identity.GetUserId<int>(), login, page);
            return View(model);
        }

        [HttpPost]
        public ActionResult Talk(string login, int page, MessageTalkDto model)
        {
            var newMsg = model.MessageCreate;

            if (!ModelState.IsValid)
            {
                model = _messageService.GetTalk(HttpContext.User.Identity.GetUserId<int>(), login, page);
                model.MessageCreate = newMsg;
                return View(model);
            }

            newMsg.FromUserId = HttpContext.User.Identity.GetUserId<int>();
            newMsg.ToUserLogin = login;
            _messageService.AddMessage(newMsg);

            return RedirectToAction("Talk", new {login = login });
        }

        [HttpPost]
        public ActionResult DeleteMessage(string login, int page, int messageId)
        {
            _messageService.DeleteMessage(HttpContext.User.Identity.GetUserId<int>(), messageId);

            return RedirectToAction("Talk", new { login = login, page = page });
        }
        

    }
}

XnForum.UI.Web/Views/Message/Messages.cshtml
@model XnForum.Services.Contracts.DTO.Message.TalksListDto

@{
    ViewBag.Title = "Messages";
    XnForum.Services.Contracts.DTO.MessageHeaderDto messageHeaderModel = null;
}

<h3>Wiadomości</h3>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => messageHeaderModel.UserLogin)
        </th>
        <th>
            @Html.DisplayNameFor(model => messageHeaderModel.ShortText)
        </th>
        <th>
            @Html.DisplayNameFor(model => messageHeaderModel.Date)
        </th>
    </tr>

    @foreach (var item in Model.Messages) {
        <tr>
            <td>
                <a href="@Url.Action("Account", "Account", new {login = item.UserLogin})">
                    @item.UserLogin
                </a>
            </td>
            <td>
                @if (item.New)
                {
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                    <strong>
                        @Html.ActionLink(item.ShortText, "Talk", new {login = item.UserLogin})
                    </strong>
                }
                else
                {
                    @Html.ActionLink(item.ShortText, "Talk", new { login = item.UserLogin })
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
    }

</table>

<nav class="container" aria-label="Page navigation">
    <ul class="pagination">
        @if (Model.Page > 1)
        {
            <li>
                <a href="@Url.Action("Messages", "Message", new { page = Model.Page - 1})" aria-label="Previous">
                    &laquo;
                </a>
            </li>
        }
        @for (int i = 1; i <= Model.PagesCount; i++)
        {
            if (i == Model.Page)
            {
                <li class="active">
                    <a href="@Url.Action("Messages", "Message", new { page = i})" aria-hidden="true">
                        @i
                    </a>
                </li>
            }
            else
            {
                <li>
                    <a href="@Url.Action("Messages", "Message", new { page = i})" aria-hidden="true">
                        @i
                    </a>
                </li>
            }

        }
        @if (Model.Page < Model.PagesCount)
        {
            <li>
                <a href="@Url.Action("Messages", "Message", new { page = Model.Page + 1})" aria-label="Next">
                    &raquo;
                </a>
            </li>
        }
    </ul>
</nav>

XnForum.UI.Web/Views/Message/Talk.cshtml
@model XnForum.Services.Contracts.DTO.MessageTalkDto

@{
    ViewBag.Title = "Talk";
}

<h3>Rozmowa z użytkownikiem @Model.UserLogin</h3>

<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.MessageCreate.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MessageCreate.Text, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MessageCreate.Text, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Wyślij wiadomość" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <hr/>
</div>

@if (Model.Messages.Any())
{
    <table class="table">
        @foreach (var message in Model.Messages)
        {
            <tr>
                <td>
                    @Html.ActionLink(message.FromUserLogin, "Account", "Account", new {login = message.FromUserLogin}, new {})
                </td>
                <td>
                    @if (message.New)
                    {
                        <strong>
                            @message.Text
                        </strong>
                    }
                    else
                    {
                        @message.Text
                    }
                </td>
                <td>
                    @message.Date
                </td>
                <td class="td-buttons">
                    @using (Html.BeginForm("DeleteMessage", "Message", new {login = Model.UserLogin, page = Model.Page}))
                    {
                        <input type="hidden" name="messageId" value="@message.Id"/>
                        <button type="submit" name="action:MessageDelete" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </button>
                    }
                </td>
            </tr>
        }
    </table>
}
else
{
    <p class="forum-info-text alert alert-info">Brak wiadomości, napisz coś</p>
}


<nav class="container" aria-label="Page navigation">
    <ul class="pagination">
        @if (Model.Page > 1)
        {
            <li>
                <a href="@Url.Action("Talk", "Message", new { login = Model.UserLogin, page = Model.Page - 1})" aria-label="Previous">
                    &laquo;
                </a>
            </li>
        }
        @for (int i = 1; i <= Model.PagesCount; i++)
        {
            if (i == Model.Page)
            {
                <li class="active">
                    <a href="@Url.Action("Talk", "Message", new { login = Model.UserLogin, page = i})" aria-hidden="true">
                        @i
                    </a>
                </li>
            }
            else
            {
                <li>
                    <a href="@Url.Action("Talk", "Message", new { login = Model.UserLogin, page = i})" aria-hidden="true">
                        @i
                    </a>
                </li>
            }

        }
        @if (Model.Page < Model.PagesCount)
        {
            <li>
                <a href="@Url.Action("Talk", "Message", new { login = Model.UserLogin, page = Model.Page + 1})" aria-label="Next">
                    &raquo;
                </a>
            </li>
        }
    </ul>
</nav>