XnForum.UI.Web/Controllers/Api/ForumController.cs
using System.Web.Http;
using XnForum.Services.Contracts.DTO;
using XnForum.Services.Contracts.Interfaces;
using XnForum.UI.Web.Helpers;

namespace XnForum.UI.Web.Controllers.Api
{
    public class ForumController : ApiController
    {
        private IForumService _forumService;

        public ForumController(IForumService forumService)
        {
            _forumService = forumService;
        }

        //main page
        public IHttpActionResult Get()
        {
            var model = _forumService.GetAllForumData();

            return Json(model, ViewHelpers.CamelCase);
        }

        //forum
        public IHttpActionResult Get(int id)
        {
            var model = _forumService.GetForum(id);

            return Json(model, ViewHelpers.CamelCase);
        }
        
    }
}

XnForum.UI.Web/Controllers/Api/ThreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using XnForum.Services.Contracts.DTO;
using XnForum.Services.Contracts.Interfaces;
using XnForum.UI.Web.Helpers;
using XnForum.UI.Web.Validation;

namespace XnForum.UI.Web.Controllers.Api
{
    public class ThreadController : ApiController
    {
        private IThreadService _threadService;

        public ThreadController(IThreadService threadService)
        {
            _threadService = threadService;
        }

        public IHttpActionResult Get(int id)
        {
            var model = _threadService.GetThread(id);
            
            return Json(model, ViewHelpers.CamelCase);
        }

        public string Post(int id, int thread, string description)
        {
            var model = new PostCreateDto();
            model.UserId = id;
            model.Text = description;
            model.ThreadId = thread;
            model.ModelState = new ModelStateWebWrapper(ModelState);

            _threadService.AddPost(model);
            if (!ModelState.IsValid)
            {
                var errorList = ModelState.Values.SelectMany(m => m.Errors)
                                 .Select(e => e.ErrorMessage)
                                 .ToList();

                return String.Join(", ", errorList);
            }

            return "ok";
        }
    }
}

XnForum.UI.Web/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XnForum.Services.Contracts.Interfaces;

namespace XnForum.UI.Web.Controllers
{
    public class ForumController : Controller
    {
        private IForumService _forumService;

        public ForumController(IForumService forumService)
        {
            _forumService = forumService;
        }

        //main page
        public ActionResult Index()
        {
            var model = _forumService.GetAllForumData();

            return View(model);
        }

        //forum
        public ActionResult Forum(int id, int page)
        {
            var model = _forumService.GetForum(id, page);

            return View(model);
        }
        
    }
}

XnForum.UI.Web/Views/Forum/Forum.cshtml
@model XnForum.Services.Contracts.DTO.ForumDto

@{
    ViewBag.Title = "Forum";
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("Index", "Forum")">Główna</a></li>
    <li><a href="@Url.Action("Index", "Forum")#cat_@Model.CategoryId">@Model.CategoryName</a></li>
    <li class="active">@Model.Name</li>
</ol>

<div class="panel panel-primary">
    <div class="panel-heading">
        @Model.Name
    </div>
    <div class="panel-body">
        @Html.ActionLink("Dodaj wątek", "Create", "Thread", new { id = Model.Id }, new { @class = "btn btn-default" })

        @if (Model.Threads.Any())
        {
            <div class="table table-responsive table-list">
                <table class="table table-striped table-responsive">
                    @foreach (var thread in Model.Threads)
                    {
                        <tr>
                            <td class="col-md-10">
                                <span class="glyphicon glyphicon-list"></span>&nbsp;
                                @Html.ActionLink(thread.Name, "Thread", "Thread", new {id = thread.Id }, null)
                            </td>
                            <td class="col-md-2">
                                @thread.UserLogin
                            </td>
                        </tr>
                    }
                </table>
            </div>
        }
        else
        {
            <p>brak wątków w tym forum</p>
        }
    </div>
</div>
<nav class="container" aria-label="Page navigation">
    <ul class="pagination">
        @if (Model.Page > 1)
        {
            <li>
                <a href="@Url.Action("Forum", "Forum", new {id = Model.Id, page = Model.Page - 1})" aria-label="Previous">
                    &laquo;
                </a>
            </li>
        }
        @for (int i = 1; i <= Model.PagesCount; i++)
        {
            if (i == Model.Page)
            {
                <li class="active">
                    <a href="@Url.Action("Forum", "Forum", new {id = Model.Id, page = i})" aria-hidden="true">
                        @i
                    </a>
                </li>
            }
            else
            {
                <li>
                    <a href="@Url.Action("Forum", "Forum", new {id = Model.Id, page = i})" aria-hidden="true">
                        @i
                    </a>
                </li>
            }

        }
        @if (Model.Page < Model.PagesCount)
        {
            <li>
                <a href="@Url.Action("Forum", "Forum", new {id = Model.Id, page = Model.Page + 1})" aria-label="Next">
                    &raquo;
                </a>
            </li>
        }
    </ul>
</nav>

XnForum.UI.Web/Views/Forum/Index.cshtml
@model XnForum.Services.Contracts.DTO.AllForumDataDto

@{
    ViewBag.Title = "Index";
}

@if (Model.AdminNotes.Any())
{
    <div>
        @foreach (var note in Model.AdminNotes)
        {
        <div class="alert alert-info">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Info:</span>
            @Html.Raw(note.Text)
        </div>
        }
    </div>
}


@foreach (var category in Model.Categories)
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            @category.Name
        </div>
        <div class="panel-body">
            <div class="table table-responsive table-list">
                <table class="table table-striped table-responsive">
                    @foreach (var forum in category.Forums)
                    {
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-th-list"></span>&nbsp;
                                @Html.ActionLink(forum.Name, "Forum", new {id = forum.Id})
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
}